{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevirt-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubevirt-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
