{{- if and .Values.rbac.create .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevirt-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
