apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net
  namespace: default
spec:
  config: |
    '{
      "cniVersion": "1.0.0",
      "type": "bridge",
      "bridge": "br0",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.10.0.10/24",
            "gateway": "10.10.0.1"
          }
        ]
      }'
