apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan2101
spec:
  config: |
    {
        "cniVersion": "1.0.0",
        "name": "br0",
        "plugins": [
            {
                "type": "bridge",
                "bridge": "br0",
                "ipam": {},
                "vlan": 2101
            },
            {
                "type": "tuning"
            }
        ]
    }
